default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: rails_user
  password: password
  pool: 5

development:
  <<: *default
  database: db/rrr_development

test:
  <<: *default
  database: db/rrr_test

production:
  <<: *default
  database: db/rrr_production
